### ISSUE TITLE
Implement Palette POST Controller

### ISSUE THREAD

**Issue by LeoBorai** [gitpullsh/simple-express-rest-crud-sample#3]
Implement a controller for the Palette model that handles the POST request.
This controller method should.
1. Receive a `Palette` object
2. Insert the object into the `palettes` collection

**Comment by jonylugos** [comment]
i take

**Comment by LeoBorai** [comment]
Te recomiendo que empieces con la ruta, con que tengas lo que viene del body del pedido esta bien.
Este es el issue #1  te lo asigno?

**Comment by jonylugos** [comment]
ok
